name: CI
on: push
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: there4/markdown-resume:2.3.1
      options: --user root
      volumes:
        - out:/mnt/out
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Make pdf (CV long)
        run: md2resume pdf --template swissen ${GITHUB_WORKSPACE}/cv_long.md .
      - name: Make html (CV long)
        run: md2resume html --template swissen ${GITHUB_WORKSPACE}/cv_long.md .
#      - name: Delete old release assets
#        uses: mknejp/delete-release-assets@v1
#        with:
#          token: ${{ github.token }}
#          tag: latest
#          assets: |
#            *.pdf
#            *.html
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_id }}
          release_name: latest
          draft: false
          prerelease: false
      - name: Release CV full PDF
        id: upload-cvfull-pdf
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./cv_long.pdf
          asset_name: CV_Touron_Xavier_Full.pdf
          asset_content_type: application/pdf
      - name: Release CV full HTML
        id: upload-cvfull-html
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./cv_long.html
          asset_name: CV_Touron_Xavier_Full.html
          asset_content_type: application/pdf
      - name: Deploy CV full HTML to git pages
        uses: ./
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          remote_url: https://github.com/appleboy/gh-pages-action.git