name: CI
on: push
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: there4/markdown-resume:2.3.1
      options: --user root
      volumes:
        - out:/mnt/out
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: CV pdf
        run: md2resume pdf --template swissen ${GITHUB_WORKSPACE}/cv_long.md /mnt/out/CV_Touron_Xavier_Full.pdf