name: CI
on: push
jobs:
  make:
    runs-on: ubuntu-latest
    container:
      image: xto34/markdown-resume:latest
      options: --user root
      volumes:
        - ${GITHUB_WORKSPACE}/assets:${PWD}/assets
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: test PWD
        run: pwd
      - name: test LS
        run: ls -lah
      - name: Make pdf (CV pdf)
        run: md2resume pdf --template swissen2 ${GITHUB_WORKSPACE}/cv.md .
      - name: Make html (CV html)
        run: md2resume html --template swissen2 ${GITHUB_WORKSPACE}/cv.md .
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_id }}
          release_name: CV
          draft: false
          prerelease: false
      - name: Release CV PDF
        id: upload-cv-pdf
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./cv.pdf
          asset_name: CV_Touron_Xavier.pdf
          asset_content_type: application/pdf
      - name: Release CV HTML
        id: upload-cv-html
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./cv.html
          asset_name: CV_Touron_Xavier.html
          asset_content_type: text/html
  deploy:
    needs: make
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Fetch Release CV
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'xtodev/cv'
          version: 'tags/${{ github.run_id }}'
          file: 'CV_Touron_Xavier.html'
          target: 'index.html'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to Github pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .