name: CI
on: push
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: there4/markdown-resume:2.3.1
      options: --user root
      volumes:
        - out:/mnt/out
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: echo workspace path
        run: echo "workspace path = ${GITHUB_WORKSPACE}"
      - name: LS workspace
        run: ls -lha ${GITHUB_WORKSPACE}
      - name: LS out folder
        run: ls -lha /mnt/out
      - name: test file
        run: touch /mnt/out/testfile
      - name: test file2
        run: touch ${GITHUB_WORKSPACE}/testfile2
      - name: Make pdf (CV long)
        run: md2resume pdf --template swissen ${GITHUB_WORKSPACE}/cv_long.md /mnt/out/CV_Touron_Xavier_Full.pdf
      - name: LS out folder
        run: ls -lha /mnt/out
      - name: LS workspace
        run: ls -lha ${GITHUB_WORKSPACE}