name: CI

on: push

jobs:
  myjob:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/my-action
    - uses: docker://there4/markdown-resume:2.3.1
      run: ./bin/md2resume pdf --template swissen cv_long.md .