name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: there4/markdown-resume:2.3.1
    steps:
      - name: CV pdf
        run: ./bin/md2resume pdf --template swissen cv_long.md .
